# Generated by Django 5.2.8 on 2025-12-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_comentario_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
