# Generated by Django 5.2.8 on 2025-12-07 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_comentario_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_favorito', to=settings.AUTH_USER_MODEL)),
                ('id_produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produto_favorito', to='produtos.produto')),
            ],
        ),
    ]
