# Generated by Django 5.2.8 on 2025-12-12 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_favorito', to='produtos.produto'),
        ),
    ]
