# Generated by Django 5.2.8 on 2025-11-21 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_favorito_id_cliente_alter_favorito_id_produto'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_favorito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_favorito', to='produtos.produto'),
        ),
    ]
