# Generated by Django 5.2.8 on 2025-12-06 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_alter_favorito_id_cliente'),
        ('produtos', '0004_comentario_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_favorito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='id_produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produto_favorito', to='produtos.produto'),
        ),
    ]
