# Generated by Django 5.2.8 on 2025-12-07 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_alter_favorito_id_cliente_alter_favorito_id_produto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
