# Generated by Django 5.2.8 on 2025-11-21 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('Percentual', '%'), ('Fixo', 'R$')])),
                ('valor', models.FloatField()),
                ('ativo', models.BooleanField()),
                ('data_inicio', models.DateTimeField()),
                ('data_expiracao', models.DateTimeField()),
                ('uso_maximo_usuario', models.IntegerField(default=1)),
                ('uso_maximo', models.IntegerField(null=True)),
                ('valor_minimo', models.FloatField(null=True)),
                ('categoria', models.ManyToManyField(to='produtos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('valor_compra', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedido_cliente', to=settings.AUTH_USER_MODEL)),
                ('produtos', models.ManyToManyField(to='produtos.produto')),
            ],
        ),
    ]
