# Generated by Django 5.2.8 on 2025-12-09 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_remove_pedido_produtos_pedido_status_sacola_and_more'),
        ('produtos', '0005_favorito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sacola',
            new_name='Cesta',
        ),
        migrations.CreateModel(
            name='ItemCesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('cesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestao.cesta')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemSacola',
        ),
    ]
