# Generated by Django 5.2.8 on 2025-12-17 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_rename_sacola_cesta_itemcesta_delete_itemsacola'),
        ('produtos', '0006_alter_favorito_id_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_pedido', to='gestao.pedido'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_pedido', to='produtos.produto'),
        ),
    ]
