# Generated by Django 5.2.8 on 2025-12-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_alter_itempedido_pedido_alter_itempedido_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor_compra',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
